import { expect, test } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'

const viewports = [
  { name: 'small-mobile', width: 360, height: 800 },
  { name: 'mobile', width: 390, height: 844 },
  { name: 'tablet', width: 768, height: 1024 },
  { name: 'small-desktop', width: 1024, height: 900 },
  { name: 'laptop', width: 1280, height: 900 },
  { name: 'desktop', width: 1440, height: 1000 },
]

for (const viewport of viewports) {
  test(`${viewport.name} landing layout has no horizontal overflow`, async ({ page }) => {
    const consoleErrors: string[] = []
    page.on('console', (message) => { if (message.type() === 'error') consoleErrors.push(message.text()) })
    page.on('pageerror', (error) => consoleErrors.push(error.message))
    await page.setViewportSize({ width: viewport.width, height: viewport.height })
    await page.goto('/', { waitUntil: 'networkidle' })
    await expect(page.getByRole('heading', { level: 1 })).toContainText('Your city listens')
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    expect(consoleErrors).toEqual([])
    for (const heading of ['What can you report?', 'See civic work moving forward', 'Civic participation without the guesswork.', 'From street-level concern to visible action']) {
      await page.getByRole('heading', { name: heading }).scrollIntoViewIfNeeded()
      await page.waitForTimeout(100)
    }
    await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }))
    await page.screenshot({ path: `test-results/${viewport.name}.png`, fullPage: true })
  })
}

test('citizen can use AI assistance, review a geospatial duplicate warning, submit, track and restore the session', async ({ page, context }) => {
  const consoleErrors: string[] = []
  page.on('console', (message) => { if (message.type() === 'error') consoleErrors.push(message.text()) })
  page.on('pageerror', (error) => consoleErrors.push(error.message))
  const suffix = Date.now()
  const email = `meera.${suffix}@civicpulse.local`

  await page.setViewportSize({ width: 1280, height: 900 })
  await context.grantPermissions(['geolocation'], { origin: 'http://127.0.0.1:4173' })
  await context.setGeolocation({ latitude: 18.5588, longitude: 73.8075 })
  await page.goto('/register', { waitUntil: 'networkidle' })
  await page.getByLabel('Full name').fill('Meera Kulkarni')
  await page.getByLabel('Email address').fill(email)
  await page.getByLabel('Mobile number').fill('+919812345678')
  await page.locator('#password').fill('CivicCity#42')
  await page.getByRole('button', { name: 'Create account' }).click()
  await expect(page).toHaveURL(/\/report$/)

  await page.getByRole('button', { name: /Pothole/ }).click()
  await page.getByRole('button', { name: 'Continue' }).click()
  await page.getByLabel('Issue description').fill('A deep pothole beside the bus shelter is forcing two-wheelers into the main traffic lane after sunset.')
  await page.getByRole('button', { name: 'Review description' }).click()
  await expect(page.getByText('Pothole', { exact: true }).last()).toBeVisible()
  await expect(page.getByText(/confidence/)).toBeVisible()
  await page.getByRole('button', { name: 'Continue' }).click()

  const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9ZpDkAAAAASUVORK5CYII=', 'base64')
  await page.locator('input[type="file"]').setInputFiles({ name: 'pothole.png', mimeType: 'image/png', buffer: png })
  await expect(page.getByText('pothole.png')).toBeVisible()
  await page.getByRole('button', { name: 'Continue' }).click()

  await page.getByRole('button', { name: 'Use current location' }).click()
  await expect(page.getByText('Map pin confirmed')).toBeVisible()
  await page.getByLabel('Street address').fill('Aundh Road near Gaikwad Nagar')
  await page.getByLabel('Landmark').fill('Beside the PMPML bus shelter')
  await page.getByLabel('City').fill('Pune')
  await page.getByLabel('State').fill('Maharashtra')
  await page.getByLabel('PIN code').fill('411007')
  await page.getByRole('button', { name: 'Continue' }).click()
  await expect(page.getByRole('heading', { name: 'Review your report' })).toBeVisible()
  await expect(page.getByText('Similar reports may already exist nearby')).toBeVisible()
  await page.getByRole('button', { name: 'Submit as a new report' }).click()

  await expect(page.getByText('Report submitted successfully')).toBeVisible()
  await expect(page.locator('p.font-mono').first()).toHaveText(/^CP-\d{4}-[A-F0-9]{12}$/)
  await expect(page.getByRole('heading', { name: 'Progress updates' })).toBeVisible()
  await expect(page.locator('img[alt]').last()).toBeVisible()
  expect(await page.locator('img[alt]').last().evaluate((image: HTMLImageElement) => image.complete && image.naturalWidth > 0)).toBe(true)
  const reference = await page.locator('p.font-mono').first().textContent()
  await page.getByRole('link', { name: 'Back to my reports' }).click()
  await expect(page).toHaveURL(/\/my-reports$/)
  await expect(page.locator('p.font-mono').filter({ hasText: reference! }).first()).toBeVisible()

  await page.getByRole('button', { name: 'Sign out Meera Kulkarni' }).click()
  await page.goto('/my-reports')
  await expect(page).toHaveURL(/\/login$/)
  await page.getByLabel('Email address').fill(email)
  await page.locator('#password').fill('CivicCity#42')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page).toHaveURL(/\/my-reports$/)
  await expect(page.locator('p.font-mono').filter({ hasText: reference! }).first()).toBeVisible()
  await page.reload({ waitUntil: 'networkidle' })
  await expect(page.locator('p.font-mono').filter({ hasText: reference! }).first()).toBeVisible()
  expect(consoleErrors).toEqual([])
})

test('civic map renders actual reports, clusters, count badges, filters and nearby results', async ({ page }) => {
  const consoleErrors: string[] = []
  page.on('console', (message) => { if (message.type() === 'error') consoleErrors.push(message.text()) })
  page.on('pageerror', (error) => consoleErrors.push(error.message))
  await page.setViewportSize({ width: 1280, height: 900 })
  await page.goto('/login', { waitUntil: 'networkidle' })
  await page.getByLabel('Email address').fill('citizen@civicpulse.local')
  await page.locator('#password').fill('CivicPulse@123')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page).toHaveURL(/\/my-reports$/)
  await page.goto('/map')
  await expect(page.getByRole('heading', { name: 'See what your neighbourhood is reporting' })).toBeVisible()
  await expect(page.locator('.leaflet-container')).toBeVisible()
  await expect(page.getByText(/visible reports?/)).toBeVisible()
  await expect(page.locator('.civic-cluster-marker').first()).toBeVisible()
  await expect(page.locator('.civic-cluster-marker, .civic-report-marker').first()).toBeVisible({ timeout: 15000 })
  await expect(page.getByLabel('Visible report counts by category')).toContainText('Pothole')

  await page.getByLabel('Category', { exact: true }).selectOption('Blocked drainage')
  await expect(page.getByText('CP-2026-PUN533')).toBeVisible()
  await page.getByLabel('Status').selectOption('Resolved')
  await expect(page.getByText('No matching reports in this view')).toBeVisible()
  await page.getByLabel('Category', { exact: true }).selectOption('All categories')
  await page.getByLabel('Status').selectOption('All statuses')
  await expect(page.getByLabel('Visible report counts by category')).toContainText('Pothole')
  await expect(page.getByText(/^[1-9]\d* visible reports?$/)).toBeVisible()
  await page.getByRole('button', { name: 'This area', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Nearby reports' })).toBeVisible()
  await expect(page.getByText(/Within 5 km, nearest first/)).toBeVisible()
  await expect.poll(() => page.locator('.leaflet-tile').evaluateAll((tiles) => tiles.length > 0 && tiles.every((tile) => (tile as HTMLImageElement).complete && (tile as HTMLImageElement).naturalWidth > 0)), { timeout: 20_000 }).toBe(true)
  await page.waitForTimeout(300)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/civic-map-desktop.png', fullPage: true })
  expect(consoleErrors).toEqual([])
})

test('Civic Assist failure is clear and never blocks manual reporting', async ({ page }) => {
  await page.goto('/login', { waitUntil: 'networkidle' })
  await page.getByLabel('Email address').fill('citizen@civicpulse.local')
  await page.locator('#password').fill('CivicPulse@123')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page).toHaveURL(/\/my-reports$/)
  await page.route('**/api/ai/report-assist', async (route) => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ message: 'Civic Assist is temporarily unavailable. You can continue reporting without it.' }) }))
  await page.goto('/report')
  await page.getByRole('button', { name: /Pothole/ }).click()
  await page.getByRole('button', { name: 'Continue' }).click()
  await page.getByLabel('Issue description').fill('A deep pothole near the crossing is creating an unsafe obstruction for two-wheelers.')
  await page.getByRole('button', { name: 'Review description' }).click()
  await expect(page.getByText('Civic Assist is temporarily unavailable. You can continue reporting without it.')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Continue' })).toBeEnabled()
})

test('citizen dashboard, nearby issues, report history and profile settings use persisted application data', async ({ page }) => {
  const consoleErrors: string[] = []
  page.on('console', (message) => { if (message.type() === 'error') consoleErrors.push(message.text()) })
  page.on('pageerror', (error) => consoleErrors.push(error.message))
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/login')
  await page.getByLabel('Email address').fill('citizen@civicpulse.local')
  await page.locator('#password').fill('CivicPulse@123')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page).toHaveURL(/\/my-reports$/)
  await expect(page.getByRole('heading', { name: 'Your civic activity' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Recent reports' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Nearby issues' })).toBeVisible()
  await expect(page.getByText('CP-2026-PUN512')).toBeVisible()
  await page.getByRole('button', { name: 'Resolved', exact: true }).click()
  await expect(page.getByText('CP-2026-MYS839').first()).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/citizen-dashboard-mobile.png', fullPage: true })

  await page.getByRole('link', { name: 'Profile & settings' }).first().click()
  await expect(page.getByRole('heading', { name: 'Profile & settings' })).toBeVisible()
  await page.getByLabel('City', { exact: true }).fill('Pune')
  await page.getByLabel('Nearby issues').check()
  await page.getByLabel('Compact dashboard').check()
  await page.getByRole('button', { name: 'Save profile and settings' }).click()
  await expect(page.getByText('Your profile and notification preferences are up to date.')).toBeVisible()
  await page.reload()
  await expect(page.getByLabel('Nearby issues')).toBeChecked()
  await expect(page.getByLabel('Compact dashboard')).toBeChecked()
  const results = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa']).analyze()
  expect(results.violations).toEqual([])
  await page.screenshot({ path: 'test-results/citizen-profile-mobile.png', fullPage: true })
  expect(consoleErrors).toEqual([])
})

test('admin manages filtered reports and citizens receive the persisted workflow update', async ({ page }) => {
  const consoleErrors: string[] = []
  page.on('console', (message) => { if (message.type() === 'error') consoleErrors.push(message.text()) })
  page.on('pageerror', (error) => consoleErrors.push(error.message))
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/login')
  await page.getByLabel('Email address').fill('admin@civicpulse.local')
  await page.locator('#password').fill('CivicPulse@123')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page).toHaveURL(/\/admin$/)
  await expect(page.getByRole('heading', { name: 'Civic service dashboard' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Service overview' })).toBeVisible()
  await page.getByLabel('Search').fill('CP-2026-PUN548')
  await page.getByLabel('Category').selectOption('Damaged streetlight')
  await page.getByLabel('Status').selectOption('Submitted')
  await page.getByLabel('Ward').selectOption('Aundh-Baner Ward')
  await page.getByRole('button', { name: 'Apply filters' }).click()
  await expect(page.getByText('1 matching report')).toBeVisible()
  await expect(page.getByText('CP-2026-PUN548')).toBeVisible()
  await page.getByRole('link', { name: 'Manage' }).click()
  await expect(page.getByRole('heading', { name: 'Assignment & workflow' })).toBeVisible()
  await page.getByLabel('Status').selectOption('In Progress')
  await page.getByLabel('Assigned officer').selectOption({ label: 'Ward Services Officer · Aundh-Baner Ward' })
  await page.getByLabel('Citizen-facing update').fill('Electrical maintenance team assigned; inspection is scheduled for tomorrow morning.')
  await page.getByRole('button', { name: 'Save workflow update' }).click()
  await expect(page.getByText('Report updated to In Progress.')).toBeVisible()
  await expect(page.getByText('Electrical maintenance team assigned; inspection is scheduled for tomorrow morning.')).toBeVisible()

  await page.setViewportSize({ width: 768, height: 1024 })
  await page.goto('/admin')
  await expect(page.getByRole('heading', { name: 'Civic service dashboard' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  let results = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa']).analyze()
  expect(results.violations).toEqual([])
  await page.screenshot({ path: 'test-results/admin-dashboard-tablet.png', fullPage: true })

  await page.getByRole('button', { name: 'Open navigation menu' }).click()
  await page.getByRole('button', { name: 'Sign out', exact: true }).click()
  await expect(page).toHaveURL(/\/login$/)
  await page.getByLabel('Email address').fill('citizen@civicpulse.local')
  await page.locator('#password').fill('CivicPulse@123')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page).toHaveURL(/\/my-reports$/)
  await expect(page.getByText('Electrical maintenance team assigned; inspection is scheduled for tomorrow morning.')).toBeVisible()
  await expect(page.getByText('CP-2026-PUN548').first()).toBeVisible()
  results = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa']).analyze()
  expect(results.violations).toEqual([])
  expect(consoleErrors).toEqual([])
})

test('mobile reporting, map and authentication screens meet automated WCAG A and AA checks', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/login', { waitUntil: 'networkidle' })
  let results = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa']).analyze()
  expect(results.violations).toEqual([])
  await page.getByLabel('Email address').fill('citizen@civicpulse.local')
  await page.locator('#password').fill('CivicPulse@123')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page).toHaveURL(/\/my-reports$/)
  await page.goto('/report')
  await expect(page.getByRole('heading', { name: 'Report a civic issue' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  results = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa']).analyze()
  expect(results.violations).toEqual([])
  await page.screenshot({ path: 'test-results/mobile-report.png', fullPage: true })
  await page.goto('/map')
  await expect(page.locator('.leaflet-container')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  results = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa']).analyze()
  expect(results.violations).toEqual([])
  await page.screenshot({ path: 'test-results/civic-map-mobile.png', fullPage: true })
})

test('mobile menu, dark theme and reduced motion work', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/', { waitUntil: 'networkidle' })
  await page.getByRole('button', { name: 'Open navigation menu' }).click()
  await expect(page.getByRole('navigation', { name: 'Mobile navigation' })).toBeVisible()
  await page.getByRole('button', { name: 'Switch to dark theme' }).click()
  await expect(page.locator('html')).toHaveClass(/dark/)
  const scrollBehavior = await page.locator('html').evaluate((element) => getComputedStyle(element).scrollBehavior)
  expect(scrollBehavior).toBe('auto')
})
